int sep = 27;
int maximg = 16;
PImage [] images = new PImage [maximg];
String estados;
String [] pantallas = {"CLICK PARA EMPEZAR EL JUEGO.", 
    "-Ettil el renegado, Ettil el cobarde. Ettil, el que no quiere participar en la gloriosa invasión\n de Marte a la Tierra. Es lo que escuchás desde la calle.\n Mientras tu mujer llora en un rincón, tu suegro entra a la casa de un portazo.\n-Así que mi yerno un traidor a la Patria.\n -¿Por qué no tratas de convencerlo padre?-dice Tylla\n  -¿Convencer a un montón de mierda? Los hombres marchan valientemente afuera mientras vos\npermanecés acá. Te debería dar vergüenza.", 
    "-¡Vayase al carajo con sus frases estúpidas! ¡Salga de mi casa!- vociferás mientras llevás al viejo a\nla puerta mediante empujones y patadas.", 
    "-Quizá tengas razón...Aunque sigo pensando que la victoria será muy complicada de conseguir.\ndecís, mientras mirás al suelo avergonzado.\n-La gloria marciana es imbatible muchacho, esos humanos no van a poder parar al Planeta Rojo.,\nTylla te da un gran abrazo.,\n-Vamos, tenés que alistarte rápido, los cohetes están despegando justo ahora- te dice tu suegro.", 
    "Un escuadrón de tres hombres de la Policía Militarizada cruza el umbral de la puerta armas en\nmano.\n-¿Ettil?- dice con voz firme el del medio.\n-Sí, soy yo.\n-Queda usted arrestado. ¡Hombres!- los otros dos soldados te esposan y te llevan arrastrando de los\ncodos.", 
    "El calabozo era limpio y claro, vacío.\nSe abre la puerta, y una especie de vehículo entra lleno de libros. El Comisionado militar entra tras\neste.\n-Ettil Vrye- te dice el comisionado con altanería-, nos gustaría saber ¿Por qué tiene todos estos\nlibros terrestres en su casa? Libros de ficción, historias maravillosas, cuentos científicos\n¡Explíquese!\n-Si me van a matar háganlo de una vez. Estos libros explican por que no quiero ir a la guerra, y por\nque la invasión fracasará.\nEl Comisionado frunció el seño.\n-¿A qué se refiere?\n-Todos estos libros hablan de una invasión a Marte, que finalmente es reprimida por un héroe\nhumano, blanco, musculoso, americano o irlandés, llamado Jick, Mick o Rick. Los humanos tienen\n una moral lo suficientemente alta como para ganarle al Ejército marciano.\n-¡Basta! ¡Traidor! Vamos a tirar al fuego estos libros, y luego lo tiraremos a usted. Eliga, Ettil Vrye,\nunirse a la Legión de Guerreros o ser ejecutado.", 
    "-Si hay que elegir entre la muerte y la muerte, elijo las llamas.\n-¡Hombres!\nLos guardias entran al calabozo y te arrastran al patio. En el medio se encuentra un gran pozo, de\ndonde surgen llamas furiosas e incandecentes.\nLos militares empiezan a tirar los libros uno por uno.\nAl otro lado del patio ves a tu hijo, con cara de miedo y tristeza\nmientras unas manos rudas te arrancan la ropa y te asoman al pozo.", 
    "-Bien, me uniré al Ejército -le decís de forma resignada al Comisionado.\n-Me alegra que recapacites, Vrye, al parecer no sos tan idiota como pensaba. Hombres, liberen al\n,prisionero.\nLos soldados abren la compuerta de la celda y te entregan la armadura y el arma para la invasión.\n-Preparate, el cohete está a punto de despegar. Mientras tanto llevaremos estos libros al pozo.", 
    "Las llamas están cada vez más cerca. Estás decidido, los intereses bélicos de los líderes marcianos\nno son los tuyos, y es mejor morir con tus convicciones antes que regalarselas a un montón de \nignorantes con poder.\nLos soldados te dejan desnudo, y en un pestaneo te lanzan al pozo. Las llamas te consumen por todo\nel cuerpo, el ardor es cada vez más intenso, y sentís como se calcina todo tu ser.\nEttil Vrye, serás recordado como el marciano que se resistió al sistema, y que el Ejército no pudo\ndoblegar. Aunque muchos te tachen de cobarde y traidor, quizá seas el martir silencioso de muchos\nmarcianos con tus mismas ideas, que dejará huella en la historia del Planeta Rojo.\nFIN.", 
    "No estás dispuesto a morir. Ni ahora ni en la Tierra. Con la agilidad de una serpiente, te lográs safar\nde los brazos de los guardias. Tumbás a uno, mientras que pateás al otro. El comisionado se trata de\ntirar encima tuyo, pero vos sos más rápido, así que te echás a correr.\n-NO TE VAS A ESCAPAR DEL EJÉRCITO MARCIANO, TRAIDOR- te grita el comisionado en\nel suelo.\nLográs llegar a la ciudad, y mientras te movés como una sombra te escabullís entre los arbustos. Ves\ncomo unidades de soldados te buscan en vehículos y a pie. Necesitás moverte rápido, o te van a\nencontrar.", 
    "Lo mejor será volver a casa, en busca de ropa y tu familia, y huír junto a ellos.\nMoviéndote rápidamente entre cajas y barriles, lográs llegar a tu casa. Entrás por la puerta, y ves a\nTylla junto a tu hijo llorando abrazados. Tylla te ve, y en vez de ponerse contenta, te mira con\ndesprecio.\n-¡¿Qué estás haciendo acá?!\n-¡Me escapé Tylla! Ahora rápido, tenemos que agarrar lo que podamos e irnos antes de que vengan\npara acá\n-Para nada Ettil. Sos un traidor del Planeta. Hubiese preferido que te echen al pozo antes de verte de\nnuevo. -te dice Tylla con lágrimas en los ojos- Entregate ahora.\n-¿Qué estás diciendo Tylla? Si me entrego me van a matar. No puedo creer que digas esto frente a\nnuestro hijo ¿Acaso te estás escuchando?\n-Entonces, que así sea.\nTylla saca la cabeza por la ventana y empieza a gritar.\n-¡Acá está! El traidor Ettil Vrye, está acá\nUna docena de soldados entran a la casa con armas, y entre golpes y samarreos te arrestan. Tylla\nmira al suelo con recelo, mientras tu hijo llora a gritos. El pozo que escupe llamas es tu final.\nEn tus últimos momentos no sabés que pensar.\nFIN.", 
    "Volver a casa puede ser peligroso, y no tenés amigos o familiares que te apoyen en la ciudad. Lo\nmejor será escapar de la urbe, rumbo a las Montañas Azules.\nDecidís correr por el descampado hasta una comuna campesina que se encuentra en el pie de la\nMontaña y rehacer tu vida allí. Ni la Policía ni el Ejército te buscarían ahí. Perdiste todo lo que\ntenías, menos tu libertad.", 
    "-Y ahora despediremos a estos valientes héroes- dice el Comisionado.\nUna marcha militar suena mientras tu mujer te mira emocionada. Tu hijo está serio. \nLa compuerta se cierra de golpe, y una válvula empieza a silbar.\n-Hacia la tierra y la destrucción- murmurás.\n-¿Qué?- pregunta alguien.\n-¡Hacia la gloriosa victoria!", 
    "Te preguntás que hacés ahí. Una cacerola celebratoria que gira en la inmensidad del espacio.\n¿A qué se parece esto? Estar lejos, muy lejos de tu mujer y tus hijos.\nTe sentís solo. Estás acompañado, pero ellos tienen cuerpo y corazón, están enteros. Lo que vos\neras, está virando entre los aires y tierras de Marte.\nUna transmisión desde la Tierra.\n-¡Bienvenidos a la Tierra!- dice la voz de la radio.\n-¡¿Qué?!- gritaron varios soldados sorprendidos.\n-¡Es una trampa!\nTe estremecés, abrís los ojos y mirás con asombro la voz invisible que brota del techo. \n-¡Bienvenidos! -declaró la amable voz-. Les damos la bienvenida con los brazos abiertos. ¡Que su\nsangrienta invasión se transforme en una eterna amistad! Hace ya muchos años, nosotros los\nterrestres, renunciamos a la guerra, destruimos nuestras bombas atómicas. Todo el planeta es suyo.\n-¡No puede ser cierto! -murmuró una voz. \n-Es una trampa. ", 
    "En la Tierra, 50 mil personas esperan la llegada de los aliens como quien observa fuegos artificiales.\n-¡Allá vienen! \n-¡Ah! -dijo la multitud. \n-¡No, son gaviotas! \nUn murmullo de desilusión. \n-¡Allá! -rugió la multitud. \nLos cohetes marcianos surgieron de la luz. El alcalde miró nerviosamente a su alrededor. \n-¿Todos preparados? \n-Sí, señor -dijo Miss California 1965. \n-Sí -dijo Miss América 1940 que había venido corriendo a sustituir a Miss América 1966 que estaba\nenferma.  \n-Sí, viejo -dijo el campeón de los recolectores de frutillas del valle de San Fernando, 1956. \n-¿Lista la banda? \nLa banda alzó sus instrumentos de cobre como si fuesen cañones. Los cohetes aterrizaron. \n-¡Ahora! \nLa banda tocó Allá voy, California, diez veces.\nDesde el mediodía hasta las 4 de la tarde, la banda estuvo tocando distintas canciones de\nbienvenida, sólo interrumpidas por los discursos pro marciano del alcalde, quien también les\nentregó la llave de la Tierra a las tropas marcianas, y se repartió comida gratis.", 
    "Te sentás a la sombra del cohete, con dos de tus compañeros. -¡Así que esto es la Tierra! \n-Yo opino que hay que matar a estas ratas sucias -dijo un marciano-. No confío en ellos. Son astutos\ncomo serpientes. ¿Por qué nos reciben de este modo? -Alzó una caja-. ¿Qué me han dado aquí? Una\nmuestra, dijeron.-El marciano leyó el marbete: BLIX, EL NUEVO JABÓN EN ESCAMAS. \nLa multitud erra a la deriva, apretada alrededor de los marcianos como en un desfile de carnaval.\nSentís frío y estás temblando más que antes. \n-¿No lo sienten? -susurra-. La tensión, la maldad de todo esto. Algo va a pasarnos. Tienen algún\nplan. Un plan sutil y horrible. Van a hacernos algo... lo sé. \n-¡Opino que hay que matarlos a todos! \n-¿Cómo vas a matar a una gente que te llama «compañero» y «querido mío»? - preguntó otro \nmarciano.", 
    "Sacudís la cabeza. -Son sinceros. Y sin embargo, siento como si nos disolviésemos lentamente en\nun tanque de ácido. Tengo miedo, de veras.-Sondeás las mentes de la multitud-. Sí, son\nverdaderamente cordiales. “Adelante, camaradas, bienvenidos”, eso nos dicen. Un montón de gente\ncomún que adora por igual a perros, gatos y marcianos. Y sin embargo... sin embargo... ", 
    "-Es cierto. Los humanos están tramando algo. Tan sólo hay que esperar las órdenes del Comisionado\npara abrir fuego contra todos ellos y borrarles esas malditas sonrisas de sus extraños rostros.", 
    "¡Tranquilos chicos! Los humanos sólo nos están dando una cálida bienvenida. Disfrutemos nuestra\nestadía en la Tierra sin problemas ni preocupaciones.", 
    "Por cortesía de las cervecerías Hagenback, se distribuyó cerveza gratis a todo el mundo. Los\nmarcianos se empezaron a sentir enfermos. Se pusieron a vomitar. Las bocas se transformaron en\nfuentes de agua sucia. El ruido de los vómitos atravesó los prados.\nTe sentís muy enfermo, por lo que te sentás bajo un sicomoro. -Una conspiración, una horrorosa\nconspiración -gruñís llevándote las manos al vientre.\n-¿Que comió? -Te pregunta el comisionado militar. \n-Algo que llamaban copos de maíz -murmurás.- y una especie de cilindro de carne, dentro de un\npan; y un líquido amarillo en un vaso frío, y algo así como un pescado... -suspirás. Se te cierran los\nojos.\nLos gemidos de los invasores marcianos se oyen en todas partes. \n-¡Maten a esas víboras! -gritó alguien débilmente. \n-Calma -dijo el comisionado-. Han exagerado su hospitalidad, nada más. Vamos, de pie. En marcha\nhacia el pueblo. Instalaremos unas cuantas guarniciones para estar más seguros.\nLos hombres se incorporaron y miraron estúpidamente a su alrededor. -¡De frente, marchen! -¡Uno,\ndos, tres, cuatro! ¡Uno, dos, tres, cuatro! ", 
    "El calor lo bañaba todo. Los pasos marcianos resonaban sobre el asfalto.\n-¡Alerta. hombres! -susurró el comisionado. \nPasaban en ese momento ante un instituto de belleza. Del interior de la casa surgió una risita furtiva.\n-¡Miren! \nUna cabeza cobriza se asomó y desapareció como una muñeca. Un ojo azul brilló e hizo un guiño\ndesde el agujero de una cerradura. \n-Una conspiración -murmurás amargamentel-. Una conspiración como les dije. \nOlores y perfumes, impulsados por los ventiladores, llenaron el aire de la calle. Las mujeres estaban\nescondidas en cavernas, con cabello ondulados en raros torbellinos y picos.\n-¡En nombre de Dios! -gritás, con los nervios deshechos-. ¡Volvamos a los cohetes! ¡Volvamos a\ncasa! ¡Nos agarrarán!¡Van a arrojarse sobre nosotros, esgrimiendo \ncajas de bombones y ejemplares de El amor y Bellezas de Hollywood! \n¡Van a inundarnos con trivialidades, a destruir nuestra sensibilidad! ¿Se\natreverían a entrar ahí? \n-¿Por qué no? -preguntaron los otros marcianos. \nA lo lejos se oyó una voz, una voz alta y aguda, una voz de mujer que decía: \n-¿No es gracioso ése del medio? \n-Los marcianos no son tan malos después de todo.\n-¡Eh, eh! ¡Yoo-hoo! ¡Marcianos! ¡Eh! ", 
    "Escapás dando gritos. Te sentás en un parque, estremeciéndote, recordando la escena. Alzás los ojos\nhacia el oscuro cielo de la noche, y te sentís muy lejos de tu casa, tan desamparado. Sentado aquí,\nentre los árboles inmóviles, podés ver a lo lejos a los guerreros marcianos que pasean por las calles,\ncon mujeres terrestres, o desaparecen en la fantasmal oscuridad de los palacios de las emociones\npequeñas, para oír allí los horribles sonidos de unas cosas blancas que se movían sobre pantallas\nblancas. Y al lado de los marcianos se sientan unas mujercitas de pelo rizado, con unas esferas de\ngoma dulce y gelatinosa entre los dientes. La cueva de los vientos... el cine.", 
    "Desenfundás tu pistola pulverizadora y apuntás a las chicas.\n-¡Alejen sus sucias garras de nosotros!\nTus compañeros te empiezan a insultar y a empujar. Incluso algunos te amenazan con sus propias\narmas. Te ves obligado a huír.", 
    "Una de las chicas se te acerca y te dice:\n-Hola hombrecito ¿Qué te parece si vamos al cine?\nSin que opongas demasiada resistencia, te tironea del brazo rumbo a un enorme edificio con letras\nrojas de neón. Su pelo lleno de ondas y brillos es imponente, y su perfume te ahoga, pero aún así te\ntratás de calmar y seguir la corriente.\nEntran a una habitación gigantesca y oscura. Al fondo hay una pantalla grande como una pared. Allí\nEntran a una habitación gigantesca y oscura. Al fondo hay una pantalla grande como una pared. Allí\nespeciales de baja calidad: alienígenas que invaden la Tierra en platos voladores metálicos y\nbrillantes. Todo te parece muy exagerado y alejado de la realidad, pero aún así lográs disfrutarlo.\nA tu lado la chica se aferra a tu brazo. A tu otro lado, un tipo viejo te mira con los ojos brillantes.", 
    "-Hola. \nVolvés la cabeza, aterrorizado. Una mujer se había sentado en el banco, masticando perezosamente\nsu pastilla de goma. \n-No se escape; no muerdo -dijo la mujer.\n-Ah -respondés.\n-¿No le gustaría ir al cine? -preguntó la mujer.", 
    "-No. \n-Ah, vamos. Todos van. \n-No -decís-. ¿No hay otra cosa que hacer en este mundo? \n-Pasear en auto. ¿No tiene auto? Podría ir a cualquie parte.\n-¿Al cine, por ejemplo? \n-¿Le parece mal? \n-No... no... \n-Ey, ¿sabe como quién habla usted? -dijo la mujer-. Como un comunista. Sí, señor. Nadie aguanta\naquí esa clase de charla, se lo aviso. Nuestro viejo sistemita no tiene nada de malo. Hasta hemos\ndejado que ustedes los marcianos nos invadan sin levantar ni siquiera el dedo meñique.\n-Y no entiendo por qué. ¿Cuál es el motivo? \n-Porque somos de gran corazón, por eso. No se olvide, de gran corazón. \nLa mujer se alejó en busca de algún otro. ", 
    "Recurriendo al poco ánimo que te queda, empezás a escribirle una carta a tu mujer, moviendo\ncuidadosamente la pluma sobre la hoja apoyada en la pierna. \nQuerida Tylla... Pero te vuelven a interrumpir. Una vieja aniñada, con una carita llena de arrugas,\npálida y redonda, sacudió una pandereta bajo tus narices obligándote a alzar los ojos. \n-Hermano -exclamó la vieja con los ojos brillantes-. ¿Has sido salvado? ", 
    "-¿Estoy en peligro? -preguntás incorporándote y dejando caer la lapicera. \n-¡En terrible peligro! -lloró la mujer, golpeando la pandereta y clavando los ojos en el cielo-. Oh,\nhermano, necesitas ser salvado, urgentemente. \n-Pienso lo mismo -decís, estremeciéndote. \n-Hoy hemos salvado a muchos. Yo misma salvé a tres marcianos. ¿No está bien? -La mujer te\nmuestra los dientes. \n-Creo que sí.\nLa vieja parecía dominada por alguna sospecha. Se inclina hacia vos y te pregunta en voz baja:\n-Hermano, ¿has sido bautizado? \n-No se -murmurás.\n-¿No lo sabes? -gritó la mujer alzando la mano y la pandereta.\n-¿Es como ser fusilado? \n-Hermano -dice la mujer-. Estás en un estado pecaminoso lamentable. Le echaremos la culpa a tu\ndescuidada educación. Apuesto a que esas escuelas de Marte son terribles... No enseñarán ninguna\nverdad. Sólo un montón de mentiras. Hermano, tenés que bautizarte si querés ser feliz.", 
    "-¿Seré feliz aun en este mundo? -preguntás.\n-No pretendas manjares en tu plato -dijo la mujer-. Conténtate con unas viejas lentejas, pues nos\nespera otro mundo mejor que éste. \n-Lo conozco -replicás.\n-Un mundo de paz -continuó la mujer. -de serenidad, de leche y miel y donde todos ríen\n-¡Si si! Ahora me doy cuenta -decís.\n-Un mundo mejor.\n-Mucho mejor. Sí, Marte es un hermoso planeta. \n-Ey -dijo la mujer, estirándose y dándote, casi, con la pandereta en la cara-, ¿te ríes de mí? \n-¿Por qué? No. -te sentís confuso y asombrado-. Pensé que hablaba usted de...\n-No de ese malvado, sucio y viejo Marte. ¡Créeme! Los hombres como tú arderán siglos y siglos, y\nsufrirán, y se cubrirán de pústulas negras, y serán horriblemente torturados.", 
    "-Reconozco que la vida en la Tierra no es nada agradable. La ha descrito usted muy bien.\n-¡Estás burlándote de mí otra vez! -gritó la mujer, enojada.\n-No, no... por favor. Soy un hombre ignorante.", 
    "-Bueno -dijo la mujer-, eres un pagano y los paganos no son gente buena. Toma esta tarjeta. Vé a \nesa dirección mañana. Te bautizaremos y serás feliz. Cantaremos y saltaremos y elevaremos juntos\nnuestras voces. Y si quieres podrás oír nuestra banda de trompetas. ¿Irás? ", 
    "¡No hable así de mi planeta! Nuestra civilización es mucho más antigua y respetada que la suya. Ese\ntal destino que describe usted para ciertos hombres ya lo están viviendo aquí mismo.\n-¿Qué está diciendo canalla? Los marcianos son tan violentos y tontos que están perdiendo una\nguerra a la que nosotros no respondimos ¿Y sabe por qué? Porque los humanos aceptamos al Señor\nen nuestros corazones. Mejor vuelva a su asqueroso y solitario planeta.\nLa cara se te llena de enojo. Te incorporás de tu asiento.\n-¡Disculpese por eso!\n-¿O qué?", 
    "-¡Ya me cansé de usted! ¡Lárguese de acá!", 
    "-¡Larguese de acá y dejeme escribir en paz! Estoy cansado de todos ustedes humanos horrendos.\n-¡Usted es un terrible pecador! No me deja más remedio que hacerle una expiación de urgencia.\nLa señora saca una cruz de madera del bolsillo y te la acerca a la frente. Probablemente un arma.\nJusto en ese momento desenfundás el arma pulverizadora y le apuntás a la cabeza. La mujer suelta\nla cruz y sale corriendo y gritando calle abajo.\n-AHHHHH PAGANOS PAGANOS TIENEN EL DEMONIO DENTRO SOCORRO- grita la vieja\na lo lejos.", 
    "-¿Es usted un marciano?- te pregunta el viejo\n-Sí, lo soy.\n-¡Oh genial! Justo el tipo que estaba buscando. Por favor, acompañame a mí auto cuando termine la\npelícula.\nDespués de un rato las luces se prenden, la gente se para y aplaude. El tipo te lleva tironeando del\nbrazo hacia la salida. Allí se encuentra un lujoso auto negro.\n¡Vamos, no se quede ahí, suba!", 
    "Aturdido, volvés a tu carta: \n“Querida Tylla: Pensar que en mi ingenuidad creí que los terrestres contraatacarían con\nfusiles y bombas. Mick, o Rick, o Jick, esos apuestos jóvenes que salvan el mundo, no\nexisten. No. Hay rubios robots de rosados cuerpos de goma, reales, pero de algún modo\nirreales; vivos, pero de algún modo automáticos, que viven en cuevas. Sus dientes son de un\ntamaño increíble. Tienen, además, una mirada fija, inmóvil, por haberse pasado\ninnumerables horas mirando películas. Sólo tienen músculos en las mandíbulas: mastican\nincesantemente unos trozos de goma. Y no sólo eso, querida Tylla, toda la civilización\nterrestre es algo semejante. Y hemos sido arrojados en esta civilización como un puñado de\nsemillas en una mezcladora de cemento. Ninguno de nosotros podría sobrevivir. Nos\nmatarán a todos, pero no con una bala, sino con un amable apretón de manos. Nos\ndestruirán a todos, pero no con un cohete, sino con un automóvil... Buenas noches, Tylla.\nDeséame buena suerte, pues moriré probablemente tratando de escapar. Besos a los\nchicos.”\nLlorando en silencio, doblás la carta y te prometés a vos mismo llevarla más tarde al correo del\ncohete.\n-Eh, usted.\nUn auto negro y alargado se acerca. Un hombre se asoma a la ventanilla. -¿Es usted marciano?\n-Sí. \n-Justo el hombre que busco. Suba, rápido... La gran ocasión de su vida. Suba. Iremos a hablar a un\nlugar tranquilo.", 
    "Como hipnotizado, abrís la puerta y entrás en el coche. El coche se aleja.\n-¿Qué deseas, E. V.? ¿Un manhattan? Dos manhattans, camarero. Okay, E. V. Yo convido. ¡Yo y los\nGrandes Estudios! No saques la cartera. Mucho gusto en conocerte, E. V. Mi nombre es R. R. Van\nPlank. Quizá has oído hablar de mí. ¿No? Bueno, chócalas igual.\nSentís como el hombre te estruja y le masajea la mano.", 
    "-Mi mamá no me deja hablar con extraños.\n-Bueno, pero tu mamá no está acá ¿O no?\n-Búsquese a un marciano lo suficientemente tonto como para subirse al vehículo de un desconocido\n¡Fuera!\nEl viejo te mira con desilución, pero finalmente se va en su coche.", 
    "Van a un bar. Una ratonera oscura, rodeados de música y camareros. Aparecieron dos copas. Todo \nhabía ocurrido tan rápidamente. Van Plank, con las manos cruzadas sobre el pecho, te observa como\na un descubrimiento.\n-E. V. -dijo al fin-, te necesito para esto. La más espléndida de mis ideas. Los marcianos invaden la\nTierra. ¿Qué necesito? Un consejero técnico. Subí a mi coche, te encontré, y aquí estamos.\n¡Alcemos las copas! Por tu salud y tu futuro. \n-Pero... -decís. \n-Sí, ya sé, necesitás dinero. Bueno, no faltará. Tengo aquí mismo una apetitosa libretita de cheques.\nBueno, te diré cómo imagino la película... Escucha. -Van Plank se inclina hacia adelante-. Para\nempezar, una escena con unos marcianos que bailan y tocan el tambor. Al fondo unas grandes\nciudades de plata... \n-Pero las ciudades marcianas no son así... \n-Deja que el viejo arregle este asunto. Bueno, ahí están los marcianos, bailando alrededor del fuego.\n-Nosotros no bailamos alrededor del fuego. \n-En esta película bailarán alrededor del fuego. Luego aparecerán unas hermosas marcianas, altas y\nrubias. \n-Las marcianas son morenas... \n-Mira, E. V., así no podremos entendernos.\nnuestras marcianas serán rubias porque... porque sí. Si no el viejo no estará contento. ¿Se te ocurre\nalgo?", 
    "Te inclinás hacia adelante y tomás al hombre por la muñeca.\n-Un momento. Quiero preguntarle algo. \n-Seguro. Adelante. \n-¿Por qué han sido tan amables con nosotros? Invadimos su planeta y nos reciben alegremente,\ncomo a unos niños que han estado extraviados durante mucho tiempo. ¿Por qué? \n-No son muy inteligentes en Marte, ¿eh? Mira, Joe, piensa un momento. Todos somos gente común,\n¿no es así? Somos tan vulgares como la basura, ¿no es cierto? Bueno, aquí en la Tierra estamos\norgullosos de ser así. Este es el siglo del hombre común, Bill, y estamos orgullosos de nuestra\nmedianía. Todo el mundo ama a todo el mundo. Los entendemos, Joe, y sabemos por qué han \ninvadido la Tierra. Sabemos que se sentían muy solos en ese frío y pequeño Marte, y que\nenvidiaban nuestras ciudades... \n-Nuestra civilización es más antigua que la de ustedes. \n-Por favor, Joe, no me gusta que me interrumpan. Déjame terminar y luego dirás todo lo que\nquieras. Como te iba diciendo, se sentían muy solos allá arriba, y bajaron a ver nuestras ciudades y\nnuestras mujeres y todo lo demás, y nosotros los recibimos con los brazos abiertos. Todos somos\nhermanos. Son hombres comunes como nosotros. Y, además, Roscoe, esta invasión puede darnos\nalgunos beneficios. Por ejemplo, esta película nos reportará una ganancia neta de un billón de\ndólares.", 
    "-Espere. Otra pregunta. \n-Largala. \n-¿Cómo se llama usted? ¿Qué quiere decir R. R.? \n-Richard Robert. \n-¿Lo llamaron alguna vez, por casualidad, Rick? \n-¿Cómo lo adivinaste, compañero? Rick, exacto.\nSuspirás, y reís. Extendés la mano. \n-¿Así que usted es Rick? ¡Rick!\n-¿Dónde está el chiste? Deja que el viejo lo sepa.\n-No lo entendería... Una broma de familia. ¡Ja, ja! -Golpeas la mesa, una y otra vez-. Así que usted\nes Rick. Que divertido. Nada de músculos prominentes, nada de fuertes mandíbulas, nada de\nrevólveres. ¡Sólo una cartera llena de dinero, unos anillos de esmeraldas, y una enorme barriga! \n-Eh, cuidado con lo que dices. No soy, quizá, un Apolo, pero... \n-Deme la mano, Rick. ¡Deseaba tanto conocerlo! Usted conquistará Marte. Armado de cocteleras, \narcos plantares, fichas de poker, bolsas de goma, gorras cuadriculadas y botellas de ron.", 
    "-Soy sólo un humilde hombre de negocios -dice Van Plank bajando modestamente los ojos-\nPero, como te decía, Marte será un gran mercado para los juegos automáticos y las historietas de\nDick Tracy. Campo virgen. ¿Nunca vieron una historieta, eh? ¡Muy bien! ¡Se van a pelear por ellas,\nmuchacho! ¡Se van a pelear! Perfumes, trajes de París, pantalones y zapatos nuevos...\n-No usamos zapatos.\n-¿Pero qué me trajeron? -preguntó R. R. con los ojos en el cielo raso-. ¿Un planeta de campesinos?\nMira, Joe, ya arreglaremos eso. Se van a avergonzar de no usar zapatos. -Oh. Van Plank te palmea.-\n¿Trato hecho? ¿Serás el director técnico de mi película? Te daremos doscientos por semana para\nempezar. Y luego aumentaremos a quinientos. ¿Qué te parece?", 
    "-Me siento enfermo -Decis. \nHabías bebido el manhattan y ahora estás pálido.\n-Caramba, lo siento. No sabía que eso podía hacerte mal. Vamos a tomar un poco de aire.\nAl aire libre, te sentís mejor.\n-¿Así que por eso nos recibieron en la Tierra? \n-Claro, hijo. Cuando un terrestre puede ganarse honestamente un dólar, míralo, desborda de\nentusiasmo. El cliente nunca se equivoca. Nada de rencores...", 
    "-¡Por supuesto! Estoy ansioso por empezar.", 
    "-Lo lamento Rick, no me interesa.\n-¡Vamos Joe! Será una gran producción, y ambos vamos a conseguir mucho dinero.\n-No es lo que me importa. El dinero humano para mí no vale nada, no veo que cosas me podrían\ninteresar comprar en su mundo. Además, hay varios miles de marcianos más que seguro estén\ninteresados en tu propuesta.\n-¡Tenés razón Gallagher! En fin, fue un gusto haberte conocido. Buenas noches y ¡Felíz invasión!\nR.R te estrecha la mano y sale corriendo en busca de algún otro marciano.", 
    "Bueno, ésta es mi tarjeta. Andá a los estudios de Hollywood mañana por la mañana, a las nueve. No\nte olvides de estar a las nueve. Es una regla de la casa. \n-¿Por qué? \n-Gallagher, eres un pájaro raro, de veras; pero me gustas. Buenas noches. ¡Feliz invasión! \nEl automóvil se alejó. Lo seguís con los ojos, incrédulo. Luego, frotándote la frente con la palma de\nla mano, echás a caminar por la calle, hacia el aeropuerto. ", 
    "-Bueno, ¿qué vas a hacer? -te preguntás a vos mismo, en voz alta. \nLos cohetes, silenciosos, resplandecían a la luz de la luna. De la ciudad llegaban los lejanos ruidos\nde las fiestas. Dejás las sombras y cruzás una ancha avenida que llegaba hasta las naves. A lo lejos\nlos guardias dormían, borrachos. Escuchás. De la ciudad llegaba el débil ruido de los automóviles,\nla música y las bocinas. \nAl cabo de un año, ¿cuántos marcianos habrían muerto enfermos del hígado, los riñones o el\ncorazón? ¿Cuántos se habrían suicidado? Te detenés en medio de la desierta avenida. Podés elegir:\nquedarte aquí, aceptar el empleo en el estudio, presentarte todas las mañanas al trabajo, como\nconsejero técnico, y al cabo de un tiempo decirle al productor que sí, de veras, había masacres en\nMarte; sí, las mujeres eran altas y rubias; sí, había danzas rituales y sacrificios; sí, sí, sí. O podés\nmeterte en un cohete y volver, solo, a Marte, y quizá pudieran irse con Tylla a vivir a las montañas\nazules y ocultarse allí un año o dos, hasta que llegasen los turistas a sacar sus instantáneas y decir\nqué bonito era todo. Sabés ya que vas a decirle a Tylla: \n-La guerra es mala, pero la paz puede ser algo horrible.\n¿Qué hacer?", 
    "-¿Quién es usted para hablar así de mí Planeta? Su Tierra es una inmundicia y habitada de personas\nhorribles como usted ¡Se puede ir muy al carajo!", 
    "-No, no iré.", 
    "Tomás la tarjeta y la cortás en varios pedazos antes de tirarla al piso.", 
    "-Haré lo posible -decís, titubeando. \nLa mujer se fue calle abajo, golpeando su pandereta, cantando hasta desgañitarse: -¡Soy tan feliz, \nsoy siempre tan feliz!", 
    "-Por supuesto, iré hoy mismo.\n-Lo lamento muchachito, a estas horas la Iglesia está cerrada. Sin embargo podés venir mañana en\nla mañana. Pero veo que estás muy emocionado, así que te voy a dejar mi Biblia para que\nempieces hoy mismo.\nLa mujer saca un librito con una cruz dorada grabada en el dorso de su bolsillo y te lo entrega.\nEsa misma noche empezás a leerlo, y sentís mucha curiosidad por sus ideas y la paz que te generan.\nJunto a otros marcianos formás un grupo religioso, tratando de sacar a los otros marcianos de la\nvida de vicios y excesos.\nFIN.", 
    "La mujer te mira muy enojada, antes de retirarse rechistando plegarias con los dientes apretados.", 
    "-Yo no quiero estar acá. Extraño mi hogar, mi familia, los marcianos de Marte, con las costumbres y\ncultura de Marte. Recorrer las calles de piedra y respirar el aire azul de la Capital.\nTe escabullís entre las bases de aterrizaje en medio de la noche. Ves a lo lejos la ciudad, llena de \nvida, de luces, de gritos y de música. Desde acá se hoye como...Una mezcladora de cemento,\nruidosa e innevitable. Abrís la compuerta, encendés el motor y despegás la enorme nave. Estás solo,\npero te sentís mucho mejor que a la llegada, dejar este horrible lugar, para volver a tu hogar, se te llena\nde alegría el pecho.\nFIN.", 
    "-Creo que lo mejor será adaptarme a la vida en la Tierra. Si tantos marcianos ya se han vuelto parte\nde la sociedad terrícola entonces ¿Por qué no yo?\nCon el tiempo conseguís un trabajo en el mundo del entretenimiento, salís con humanos y\nmarcianos a fiestas, al cine, a andar en auto. La comida chatarra y las golosinas te encantan. Sos un\nterrícola más, absorbido por la mezcladora de cemento.\nFIN.", 
    "Te detenés en la ancha avenida. Volvés la cabeza y no te sorprendés al ver que un coche viene hacia\nvos, haciendo eses; un coche abierto, lleno de muchachos y muchachas vociferantes, de no más de\ndieciséis años. Ves que los ocupantes del coche te señalan con el dedo y gritan. Oís el ruido\ncreciente del motor. El coche se precipita hacia vos a noventa kilómetros por hora. Echás a correr.\nSí, sí, pensás cansadamente, con el coche ya encima, qué raro, qué triste. Suena como... una\nmezcladora de cemento.\nFIN."
  };


void setup() {
  textSize(20);
  imageMode(CENTER);
  size (800, 600);
  background(0);
  fill(255);
}

void draw(){
estados = "menu";
for (int i=0; i<images.length; i++) {
  images[i] = loadImage ("esc"+i+".PNG");
}

if (estados.equals("menu")) {
  image(images[6], width/2, height/2);
  botones(550,450,200,100);
  text(pantallas[0], sep, sep);
  text("empezar", 600, 500);
}
if (estados.equals("escena1")) {
  image(images[0], width/2, height/2);
  text(pantallas[1], sep, sep);
  botones(600,300,30,100);
  botones(200,300,30,100);
  text("pelear", 600, 500);
  text("unirse", 350, 500);
}
}

void mousePressed(){
 if (clickBoton(mouseX, mouseY, 550,450,200,100) && estados.equals("menu")){
  estados = "escena1"; 
 }
}
